# Generated by Django 5.2.4 on 2025-07-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="Check_Out",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if you are checking out for the day.",
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="checkout_time",
            field=models.DateTimeField(
                blank=True, help_text="The time you checked out for the day.", null=True
            ),
        ),
    ]
