# Generated by Django 5.2.4 on 2025-08-01 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0003_checkin_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The Django user this check-in is for (optional - person may not have a user account)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
