# Generated by Django 5.2.4 on 2025-08-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0006_userprofile_drivers_license_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_1",
                    models.CharField(help_text="Street address line 1", max_length=100),
                ),
                (
                    "street_2",
                    models.CharField(
                        blank=True,
                        help_text="Street address line 2 (optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("city", models.CharField(help_text="City name", max_length=50)),
                (
                    "state",
                    models.CharField(help_text="State abbreviation (e.g., CA, NY)", max_length=2),
                ),
                ("zip_code", models.CharField(help_text="ZIP code", max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Latitude coordinate (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Longitude coordinate (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Your normalized home address",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="checkin.address",
            ),
        ),
    ]
