services:
  neteoc-web:
    image: neteoc/web:latest
    container_name: neteoc-web
    ports:
      - "8123:8000"
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      DJANGO_DEVELOPMENT_MODE: ${DJANGO_DEVELOPMENT_MODE}
      LOGLEVEL: ${LOGLEVEL}
    env_file:
      - .env
