[project]
name = "neteoc-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django-tiles-gl>=0.3.9",
    "django>=5.1.2",
    "geopy>=2.4.1",
    "psycopg[binary]>=3.2.3",
]
