"""
Django settings for neteoc project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url

from dj_easy_log import load_loguru
from loguru import logger


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=True, cast=bool)


def setup_loguru(logger, settings_dict):
    if DEBUG:
        logger.add("netoc.log", rotation="10 MB")


if DEBUG:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
            },
        },
        "loggers": {
            "allauth": {
                "handlers": ["console"],
                "level": "DEBUG",
            },
            "allauth.socialaccount": {
                "handlers": ["console"],
                "level": "DEBUG",
            },
        },
    }


load_loguru(globals(), configure_func=setup_loguru)


logger.debug("Loguru is running")

MAINTENANCE_MODE_STATE_BACKEND = "maintenance_mode.backends.DefaultStorageBackend"
MAINTENANCE_MODE_IGNORE_ADMIN = False
MAINTENANCE_MODE_IGNORE_STAFF = False
MAINTENANCE_MODE_IGNORE_SUPERUSER = False
MAINTENANCE_MODE_RETRY_AFTER = 240


# Build paths inside the project like this: BASE_DIR / 'subdir'.
PROJECT_DIR = Path(__file__).resolve()
BASE_DIR = PROJECT_DIR.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", cast=str)


DEFAULT_ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


ALLOWED_HOSTS = config("DJANGO_ALLOWED_HOSTS", default=DEFAULT_ALLOWED_HOSTS, cast=str).split(",")

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = config(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default=",".join(DEFAULT_ALLOWED_HOSTS),
    cast=lambda v: [x.strip() for x in v.split(",")],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "organizations",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.gis",
    "allauth_ui",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.saml",
    "widget_tweaks",
    "slippers",
    "django_bootstrap5",
    "maintenance_mode",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "django_tables2",
    "rest_framework",
    "modelcluster",
    "taggit",
    "theme",
    "home",
    "operations",
    "user_profile",
]

AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

MAINTENANCE_MODE_STATE_BACKEND = "maintenance_mode.backends.DefaultStorageBackend"
MAINTENANCE_MODE_IGNORE_ADMIN = True
MAINTENANCE_MODE_IGNORE_STAFF = True
MAINTENANCE_MODE_IGNORE_SUPERUSER = True
MAINTENANCE_MODE_RETRY_AFTER = 240


# if DEBUG:
# Add django_browser_reload only in DEBUG mode
# INSTALLED_APPS += ["django_browser_reload"]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

# if DEBUG:
# Add django_browser_reload middleware only in DEBUG mode
# MIDDLEWARE += [
#     "django_browser_reload.middleware.BrowserReloadMiddleware",
# ]

ROOT_URLCONF = "neteoc.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "operations.context_processors.organization_context",
            ],
        },
    },
]

WSGI_APPLICATION = "neteoc.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {"default": dj_database_url.parse(config("DATABASE_URL", cast=str))}

# Note: For full spatial support, configure PostGIS or SpatiaLite when ready
# DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.spatialite'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MBTILES_DATABASE = BASE_DIR / "demo" / "data" / "berlin.mbtiles"

CLOUDFLARE_R2_CONFIG_OPTIONS = {
    "access_key": config("AWS_ACCESS_KEY_ID"),
    "secret_key": config("AWS_SECRET_ACCESS_KEY"),
    "bucket_name": config("AWS_STORAGE_BUCKET_NAME"),
    # "default_acl": 'public-read',
    "file_overwrite": False,
    "region_name": config("AWS_S3_REGION_NAME"),
    # "location": config("AWS_LOCATION"),
    "endpoint_url": config("AWS_S3_ENDPOINT_URL"),
    "addressing_style": "path",
    # "custom_domain": config("AWS_S3_CUSTOM_DOMAIN"),
    "querystring_auth": True,
    "signature_version": "s3v4",
}

CLOUDFLARE_R2_CONFIG_OPTIONS_STATIC = {
    "default_acl": "public-read",
    "location": f"{config('AWS_LOCATION')}/staticfiles/",
    # "custom_domain": config("AWS_S3_CUSTOM_DOMAIN"),
}
CLOUDFLARE_R2_CONFIG_OPTIONS_STATIC.update(CLOUDFLARE_R2_CONFIG_OPTIONS)

CLOUDFLARE_R2_CONFIG_OPTIONS_MEDIA = {
    "default_acl": "private",
    "location": f"{config('AWS_LOCATION')}/media/",
}
CLOUDFLARE_R2_CONFIG_OPTIONS_MEDIA.update(CLOUDFLARE_R2_CONFIG_OPTIONS)


STORAGES = {
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS_STATIC,
    },
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS_MEDIA,
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"


MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings
WAGTAIL_SITE_NAME = "NetEOC"
WAGTAILADMIN_BASE_URL = "http://127.0.0.1:8000"
WAGTAILDOCS_EXTENSIONS = [
    "csv",
    "docx",
    "key",
    "odt",
    "pdf",
    "pptx",
    "rtf",
    "txt",
    "xlsx",
    "zip",
]


# SAML/Allauth specific settings
ACCOUNT_EMAIL_VERIFICATION = "none"  # Disable email verification for SAML users
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True

# Login/Logout URL constants
ACCOUNTS_LOGIN_URL = "/accounts/login/"

SOCIALACCOUNT_ADAPTER = "home.provider.SocialAccountAdapter"
LOGIN_URL = ACCOUNTS_LOGIN_URL
WAGTAILADMIN_LOGIN_URL = ACCOUNTS_LOGIN_URL
LOGOUT_REDIRECT_URL = ACCOUNTS_LOGIN_URL
LOGIN_REDIRECT_URL = "/accounts/"
ALLAUTH_UI_THEME = "light"


# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "100/day", "user": "1000/day"},
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
}
