# Generated by Django 5.2.4 on 2025-08-01 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_1",
                    models.CharField(help_text="Street address line 1", max_length=100),
                ),
                (
                    "street_2",
                    models.CharField(
                        blank=True,
                        help_text="Street address line 2 (optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("city", models.CharField(help_text="City name", max_length=50)),
                (
                    "state",
                    models.CharField(help_text="State abbreviation (e.g., CA, NY)", max_length=2),
                ),
                ("zip_code", models.CharField(help_text="ZIP code", max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Latitude coordinate (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Longitude coordinate (WGS84)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "location_accuracy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXACT", "Exact"),
                            ("APPROXIMATE", "Approximate"),
                            ("CITY", "City Level"),
                            ("ZIP", "ZIP Code Level"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        help_text="Accuracy level of the geographic location",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "geocoded_at",
                    models.DateTimeField(
                        blank=True, help_text="When the address was geocoded", null=True
                    ),
                ),
                (
                    "geocoding_source",
                    models.CharField(
                        blank=True,
                        help_text="Source used for geocoding (e.g., Google, OpenStreetMap)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "indexes": [
                    models.Index(fields=["state", "city"], name="user_profil_state_46e734_idx"),
                    models.Index(fields=["zip_code"], name="user_profil_zip_cod_cf6de1_idx"),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="user_profil_latitud_5b7f02_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roster_id",
                    models.CharField(
                        blank=True,
                        help_text="Your default roster ID (e.g., DOE1234)",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "drivers_license_id",
                    models.CharField(
                        blank=True,
                        help_text="Your driver's license ID number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "home_address",
                    models.TextField(
                        blank=True,
                        help_text="Your home address (street, city, state, zip)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        help_text="Your normalized home address",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_profiles",
                        to="user_profile.address",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
