# Generated by Django 5.2.4 on 2025-08-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="public_bio",
            field=models.TextField(blank=True, help_text="Short public bio", null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="public_bio_visible",
            field=models.BooleanField(default=True, help_text="Show bio in public profile"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="public_email",
            field=models.EmailField(
                blank=True, help_text="Public email address", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="public_email_visible",
            field=models.BooleanField(default=False, help_text="Show email in public profile"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="public_phone",
            field=models.CharField(
                blank=True, help_text="Public phone number", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="public_phone_visible",
            field=models.BooleanField(default=False, help_text="Show phone in public profile"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="public_visible",
            field=models.BooleanField(
                default=False,
                help_text="Is public profile info visible to org members and incident check-ins?",
            ),
        ),
    ]
