# Generated by Django 5.2.4 on 2025-08-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_userprofile_public_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="geocoding_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Source used for geocoding (e.g., Google, OpenStreetMap)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="location_accuracy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXACT", "Exact"),
                    ("APPROXIMATE", "Approximate"),
                    ("CITY", "City Level"),
                    ("ZIP", "ZIP Code Level"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="",
                help_text="Accuracy level of the geographic location",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_2",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Street address line 2 (optional)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="drivers_license_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your driver's license ID number",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="home_address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Your home address (street, city, state, zip)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="public_bio",
            field=models.TextField(
                blank=True, default="", help_text="Short public bio"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="public_email",
            field=models.EmailField(
                blank=True, default="", help_text="Public email address", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="public_phone",
            field=models.CharField(
                blank=True, default="", help_text="Public phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="roster_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your default roster ID (e.g., DOE1234)",
                max_length=7,
            ),
        ),
    ]
