# Generated by Django 5.2.4 on 2025-08-04 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0011_timeentry"),
        ("user_profile", "0003_alter_address_geocoding_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gravatar_email",
            field=models.EmailField(
                blank=True,
                help_text="Email for Gravatar (defaults to account email)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="use_gravatar",
            field=models.BooleanField(default=True, help_text="Use Gravatar for profile photo"),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("PHONE", "Phone")],
                        help_text="Type of contact information",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Contact value (email address or phone number)",
                        max_length=100,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary contact for this type?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization context (null = global contact)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.incidentorganization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["contact_type", "-is_primary", "value"],
                "indexes": [
                    models.Index(
                        fields=["user", "organization"],
                        name="user_profil_user_id_e970c8_idx",
                    ),
                    models.Index(
                        fields=["is_primary", "is_active"],
                        name="user_profil_is_prim_91299e_idx",
                    ),
                    models.Index(
                        fields=["contact_type", "is_active"],
                        name="user_profil_contact_b0d537_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("is_primary", True)),
                        fields=("user", "organization", "contact_type"),
                        name="unique_primary_contact",
                    )
                ],
                "unique_together": {("user", "organization", "contact_type", "value")},
            },
        ),
    ]
