# Generated by Django 5.2.4 on 2025-08-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0005_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="drivers_license_id",
            field=models.CharField(
                blank=True,
                help_text="Your driver's license ID number",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="home_address",
            field=models.TextField(
                blank=True,
                help_text="Your home address (street, city, state, zip)",
                null=True,
            ),
        ),
    ]
