# Generated by Django 5.2.4 on 2025-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0007_address_userprofile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="geocoded_at",
            field=models.DateTimeField(
                blank=True, help_text="When the address was geocoded", null=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="geocoding_source",
            field=models.CharField(
                blank=True,
                help_text="Source used for geocoding (e.g., Google, OpenStreetMap)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="location_accuracy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXACT", "Exact"),
                    ("APPROXIMATE", "Approximate"),
                    ("CITY", "City Level"),
                    ("ZIP", "ZIP Code Level"),
                    ("UNKNOWN", "Unknown"),
                ],
                help_text="Accuracy level of the geographic location",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude coordinate (WGS84)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude coordinate (WGS84)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["state", "city"], name="checkin_add_state_116647_idx"),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["zip_code"], name="checkin_add_zip_cod_ac3216_idx"),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["latitude", "longitude"], name="checkin_add_latitud_ca5b0a_idx"
            ),
        ),
    ]
