# Generated by Django 5.2.4 on 2025-08-01 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "roster_id",
                    models.CharField(help_text="Example: DOE1234", max_length=7),
                ),
                (
                    "mileage",
                    models.IntegerField(
                        help_text="Round trip miles driven today.Rounded to nearest mile i.e. 123"
                    ),
                ),
                (
                    "food_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Dollar amount spent on food today. i.e. 12.34",
                        max_digits=10,
                    ),
                ),
                (
                    "other_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Dollar amount spent on other expenses today. i.e. 64.88",
                        max_digits=10,
                    ),
                ),
                (
                    "expense_notes",
                    models.TextField(
                        blank=True,
                        help_text="Explain any large expenses or unusual mileage.",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "Check_Out",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box if you are checking out for the day.",
                    ),
                ),
                (
                    "checkout_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time you checked out for the day.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Django user this check-in is for (optional - person may not have a user account)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
