# Generated by Django 5.2.4 on 2025-08-01 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkin",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Check-in",
                "verbose_name_plural": "Check-ins",
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the incident (e.g., 'Hurricane Milton Response', 'County Fair 2025')",
                        max_length=200,
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("HURRICANE", "Hurricane"),
                            ("FLOOD", "Flood"),
                            ("WILDFIRE", "Wildfire"),
                            ("EARTHQUAKE", "Earthquake"),
                            ("TORNADO", "Tornado"),
                            ("WINTER_STORM", "Winter Storm"),
                            ("FESTIVAL", "Community Festival"),
                            ("TRAINING", "Training Exercise"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of incident or event",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the incident",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("STANDBY", "Standby"),
                        ],
                        default="ACTIVE",
                        help_text="Current status of the incident",
                        max_length=10,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the incident began or is scheduled to begin",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the incident ended (leave blank if ongoing)",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Primary location of the incident",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who created this incident",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="checkin",
            name="incident",
            field=models.ForeignKey(
                help_text="The incident this check-in is associated with",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="operations.incident",
            ),
        ),
    ]
