# Generated by Django 5.2.4 on 2025-08-01 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_alter_checkin_options_incident_checkin_incident"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="owner",
            field=models.ForeignKey(
                default=1,
                help_text="The user who owns and has full control over this incident",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="checkin",
            name="expense_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Explain any large expenses or unusual mileage.",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="incident",
            field=models.ForeignKey(
                default=1,
                help_text="The incident this check-in is associated with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="operations.incident",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="incident",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional details about the incident",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Primary location of the incident",
                max_length=200,
            ),
        ),
    ]
