# Generated by Django 5.2.4 on 2025-08-01 18:07

from django.db import migrations


def set_incident_owners(apps, schema_editor):
    """Set owner field for existing incidents"""
    incident_model = apps.get_model("operations", "Incident")
    user_model = apps.get_model("auth", "User")

    # Get all incidents
    incidents = incident_model.objects.all()

    for incident in incidents:
        if incident.created_by:
            # If incident has a created_by user, use that as owner
            incident.owner = incident.created_by
        else:
            # If no created_by, use the first superuser
            first_superuser = user_model.objects.filter(is_superuser=True).first()
            if first_superuser:
                incident.owner = first_superuser
            else:
                # If no superuser exists, use the first user
                first_user = user_model.objects.first()
                if first_user:
                    incident.owner = first_user
                else:
                    # Skip if no users exist (should not happen in normal usage)
                    continue
        incident.save()


def reverse_set_incident_owners(apps, schema_editor):
    """Reverse migration - nothing to do since we're just setting data"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0003_add_incident_owner"),
    ]

    operations = [
        migrations.RunPython(set_incident_owners, reverse_set_incident_owners),
    ]
