# Generated by Django 5.2.4 on 2025-08-01 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0004_set_incident_owners"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="incident_commander",
            field=models.ForeignKey(
                blank=True,
                help_text="The incident commander - primary point of contact for this incident",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commanded_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
