# Generated by Django 5.2.4 on 2025-08-01 19:16

import django.db.models.deletion
import django.utils.timezone
import organizations.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0005_add_incident_commander"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The name of the organization", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created",
                    organizations.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    organizations.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "slug",
                    organizations.fields.SlugField(
                        blank=True,
                        editable=False,
                        help_text="The name in all lowercase, suitable for URL identification",
                        max_length=200,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("FIRE", "Fire Department"),
                            ("POLICE", "Police Department"),
                            ("EMS", "Emergency Medical Services"),
                            ("EMERGENCY_MGMT", "Emergency Management"),
                            ("PUBLIC_WORKS", "Public Works"),
                            ("VOLUNTEER", "Volunteer Organization"),
                            ("NGO", "Non-Governmental Organization"),
                            ("PRIVATE", "Private Company"),
                            ("FEDERAL", "Federal Agency"),
                            ("STATE", "State Agency"),
                            ("LOCAL", "Local Government"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type of organization",
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email for the organization",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Physical address of the organization"),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Organization website URL"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this organization has been verified by system administrators",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AddField(
            model_name="incident",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization that owns this incident",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="operations.incidentorganization",
            ),
        ),
        migrations.CreateModel(
            name="IncidentOrganizationInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.UUIDField(editable=False)),
                (
                    "invitee_identifier",
                    models.CharField(
                        help_text="The contact identifier for the invitee, email, phone number, social media handle, etc.",
                        max_length=1000,
                    ),
                ),
                (
                    "created",
                    organizations.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    organizations.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("INCIDENT_MANAGER", "Incident Manager"),
                            ("RESPONDER", "Responder"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="VIEWER",
                        help_text="Role the user will have when they accept the invitation",
                        max_length=20,
                    ),
                ),
                (
                    "can_create_incidents",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the invited user will be able to create incidents",
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the invited user will be able to manage other users",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_invites",
                        to="operations.incidentorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Invitation",
                "verbose_name_plural": "Organization Invitations",
            },
        ),
        migrations.CreateModel(
            name="IncidentOrganizationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    organizations.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    organizations.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("INCIDENT_MANAGER", "Incident Manager"),
                            ("RESPONDER", "Responder"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="VIEWER",
                        help_text="User's role within the organization",
                        max_length=20,
                    ),
                ),
                (
                    "can_create_incidents",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this user can create new incidents for the organization",
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this user can invite/manage other users in the organization",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_users",
                        to="operations.incidentorganization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization User",
                "verbose_name_plural": "Organization Users",
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.CreateModel(
            name="IncidentOrganizationOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    organizations.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    organizations.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to="operations.incidentorganization",
                    ),
                ),
                (
                    "organization_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.incidentorganizationuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Owner",
                "verbose_name_plural": "Organization Owners",
            },
        ),
        migrations.AddField(
            model_name="incidentorganization",
            name="users",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s",
                through="operations.IncidentOrganizationUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
