# Generated by Django 5.2.4 on 2025-08-01 19:16

from django.db import migrations


def create_default_organization(apps, schema_editor):
    """Create a default organization and assign existing incidents to it"""
    incident_organization = apps.get_model("operations", "IncidentOrganization")
    incident_organization_user = apps.get_model("operations", "IncidentOrganizationUser")
    incident_organization_owner = apps.get_model("operations", "IncidentOrganizationOwner")
    incident = apps.get_model("operations", "Incident")

    # Create a default organization
    default_org, _ = incident_organization.objects.get_or_create(
        name="Default Organization",
        defaults={
            "organization_type": "OTHER",
            "is_verified": True,
        },
    )

    # Assign all existing incidents to the default organization
    for incident_obj in incident.objects.filter(organization__isnull=True):
        incident_obj.organization = default_org
        incident_obj.save()

        # Add the incident owner as an admin of the default organization if not already there
        if incident_obj.owner:
            org_user, _ = incident_organization_user.objects.get_or_create(
                organization=default_org,
                user=incident_obj.owner,
                defaults={
                    "role": "ADMIN",
                    "can_create_incidents": True,
                    "can_manage_users": True,
                    "is_admin": True,
                },
            )

            # Make the first user the owner of the organization
            if not hasattr(default_org, "owner") or not default_org.owner:
                incident_organization_owner.objects.get_or_create(
                    organization=default_org, organization_user=org_user
                )


def reverse_default_organization(apps, schema_editor):
    """Reverse the default organization setup"""
    incident_organization = apps.get_model("operations", "IncidentOrganization")

    # Delete the default organization (this will cascade to related objects)
    try:
        default_org = incident_organization.objects.get(name="Default Organization")
        default_org.delete()
    except incident_organization.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0006_create_organization_models"),
    ]

    operations = [
        migrations.RunPython(
            create_default_organization,
            reverse_default_organization,
        ),
    ]
