# Generated by Django 5.2.4 on 2025-08-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0007_setup_default_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="organization",
            field=models.ForeignKey(
                default=1,
                help_text="The organization that owns this incident",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="operations.incidentorganization",
            ),
            preserve_default=False,
        ),
    ]
