# Generated by Django 5.2.4 on 2025-08-01 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0008_make_organization_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="parent_incident",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent incident that this incident supports or is related to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_incidents",
                to="operations.incident",
            ),
        ),
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the support request", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of what support is needed"),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        help_text="Urgency level of the request",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DECLINED", "Declined"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the support request",
                        max_length=10,
                    ),
                ),
                (
                    "requested_start_date",
                    models.DateTimeField(help_text="When support is needed to start"),
                ),
                (
                    "requested_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When support is expected to end (optional)",
                        null=True,
                    ),
                ),
                (
                    "response_notes",
                    models.TextField(blank=True, help_text="Notes from the reviewing organization"),
                ),
                (
                    "approved_resources",
                    models.TextField(
                        blank=True,
                        help_text="Description of what resources were approved",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was reviewed", null=True
                    ),
                ),
                (
                    "related_incident",
                    models.ForeignKey(
                        help_text="The incident that needs support",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_requests",
                        to="operations.incident",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="User who created this support request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requesting_organization",
                    models.ForeignKey(
                        help_text="Organization requesting support",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_support_requests",
                        to="operations.incidentorganization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_organization",
                    models.ForeignKey(
                        help_text="Organization being asked to provide support",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_support_requests",
                        to="operations.incidentorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Request",
                "verbose_name_plural": "Support Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="incident",
            name="support_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Support request that led to the creation of this incident",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_incidents",
                to="operations.supportrequest",
            ),
        ),
        migrations.CreateModel(
            name="IncidentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            (
                                "SUPPORTS",
                                "Supports - this incident supports the linked incident",
                            ),
                            (
                                "SUPPORTED_BY",
                                "Supported By - this incident is supported by the linked incident",
                            ),
                            (
                                "COORDINATES",
                                "Coordinates - incidents are coordinating together",
                            ),
                            (
                                "RELATED",
                                "Related - incidents are related but not directly supporting",
                            ),
                        ],
                        help_text="Type of relationship between incidents",
                        max_length=15,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the relationship"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this link",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_incident",
                    models.ForeignKey(
                        help_text="The incident this link originates from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="operations.incident",
                    ),
                ),
                (
                    "to_incident",
                    models.ForeignKey(
                        help_text="The incident this link points to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="operations.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Link",
                "verbose_name_plural": "Incident Links",
                "unique_together": {("from_incident", "to_incident", "relationship_type")},
            },
        ),
    ]
