# Generated by Django 5.2.4 on 2025-08-02 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0009_incident_parent_incident_supportrequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the asset category", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this asset category"),
                ),
                (
                    "requires_license",
                    models.BooleanField(
                        default=False,
                        help_text="Whether assets in this category require a license to operate",
                    ),
                ),
                (
                    "requires_training",
                    models.BooleanField(
                        default=False,
                        help_text="Whether assets in this category require special training",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asset Category",
                "verbose_name_plural": "Asset Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Unique identifier for the asset (asset tag, serial number, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name or model of the asset", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description of the asset"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In Use"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("RETIRED", "Retired"),
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged"),
                        ],
                        default="AVAILABLE",
                        help_text="Current status of the asset",
                        max_length=15,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Current location of the asset",
                        max_length=200,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Serial number of the asset",
                        max_length=100,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, help_text="Date the asset was purchased", null=True
                    ),
                ),
                (
                    "warranty_expiration",
                    models.DateField(blank=True, help_text="Date the warranty expires", null=True),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase or estimated value of the asset",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        help_text="Radio frequency (for radio assets)",
                        max_length=50,
                    ),
                ),
                (
                    "call_sign",
                    models.CharField(
                        blank=True,
                        help_text="Call sign (for radio assets)",
                        max_length=20,
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        blank=True,
                        help_text="License plate number (for vehicle assets)",
                        max_length=20,
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        help_text="Vehicle Identification Number (for vehicle assets)",
                        max_length=17,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of fuel used (for vehicle assets)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_holder",
                    models.ForeignKey(
                        blank=True,
                        help_text="User currently holding this asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Incident this asset is currently being used for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_in_use",
                        to="operations.incident",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="operations.incidentorganization",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this asset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="operations.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["identifier", "name"],
                "unique_together": {("organization", "identifier")},
            },
        ),
        migrations.CreateModel(
            name="AssetCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True,
                        help_text="Purpose or reason for checking out the asset",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending - Waiting for new holder to accept"),
                            ("ACTIVE", "Active - Asset is checked out"),
                            ("COMPLETED", "Completed - Asset has been checked back in"),
                            ("CANCELLED", "Cancelled - Checkout was cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the checkout",
                        max_length=10,
                    ),
                ),
                (
                    "checkout_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the checkout was initiated"
                    ),
                ),
                (
                    "accepted_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the new holder accepted the asset",
                        null=True,
                    ),
                ),
                (
                    "checkin_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the asset was checked back in",
                        null=True,
                    ),
                ),
                (
                    "checkout_condition",
                    models.TextField(blank=True, help_text="Condition of the asset at checkout"),
                ),
                (
                    "checkin_condition",
                    models.TextField(blank=True, help_text="Condition of the asset at checkin"),
                ),
                (
                    "issues_reported",
                    models.TextField(
                        blank=True,
                        help_text="Any issues or damage reported during checkout",
                    ),
                ),
                (
                    "checkout_location",
                    models.CharField(
                        blank=True,
                        help_text="Location where checkout occurred",
                        max_length=200,
                    ),
                ),
                (
                    "checkin_location",
                    models.CharField(
                        blank=True,
                        help_text="Location where checkin occurred",
                        max_length=200,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset being checked out",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkouts",
                        to="operations.asset",
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        help_text="User who initiated the checkout (current holder)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_checkouts_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checked_out_to",
                    models.ForeignKey(
                        help_text="User receiving the asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_checkouts_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Incident the asset is being checked out for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_checkouts",
                        to="operations.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Checkout",
                "verbose_name_plural": "Asset Checkouts",
                "ordering": ["-checkout_time"],
            },
        ),
    ]
