# Generated by Django 5.2.4 on 2025-08-02 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0010_assetcategory_asset_assetcheckout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date the work was performed")),
                (
                    "activity_description",
                    models.TextField(help_text="Description of the work performed"),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hours spent on work activities",
                        max_digits=4,
                    ),
                ),
                (
                    "volunteer_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hours spent on volunteer activities",
                        max_digits=4,
                    ),
                ),
                (
                    "travel_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hours spent traveling",
                        max_digits=4,
                    ),
                ),
                (
                    "travel_miles",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Miles traveled",
                        max_digits=8,
                    ),
                ),
                (
                    "travel_meal_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost of meals during travel",
                        max_digits=8,
                    ),
                ),
                (
                    "billeting_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost of lodging/billeting",
                        max_digits=8,
                    ),
                ),
                (
                    "purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost of purchases made",
                        max_digits=8,
                    ),
                ),
                (
                    "purchase_explanation",
                    models.TextField(
                        blank=True, help_text="Explanation of purchases made and reason"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        help_text="Incident the work was related to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operations.incident",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization the work was performed for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.incidentorganization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the work",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Entry",
                "verbose_name_plural": "Time Entries",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("user", "organization", "date")},
            },
        ),
    ]
